In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [93]:
df=pd.read_csv("customer.csv")

In [94]:
df.shape

(440833, 12)

In [95]:
df[df.isnull().any(axis=1)]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [97]:
df.tail()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [99]:
df.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [100]:
df["Churn"].value_counts()

Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

In [101]:
df["CustomerID"].isnull().sum()

np.int64(1)

In [102]:
df.dropna()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [103]:
df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [104]:
df=df.dropna()

In [105]:
df.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [106]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [107]:
df["Subscription Type"].value_counts()

Subscription Type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: int64

In [108]:
df["Contract Length"].value_counts()

Contract Length
Annual       177198
Quarterly    176530
Monthly       87104
Name: count, dtype: int64

In [109]:
df["Gender"].value_counts()

Gender
Male      250252
Female    190580
Name: count, dtype: int64

In [110]:
data=df.drop("Churn",axis=1)

In [111]:
data_labels=df["Churn"].copy()

In [112]:
data

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0
...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0

In [113]:
data_labels

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
440828    0.0
440829    0.0
440830    0.0
440831    0.0
440832    0.0
Name: Churn, Length: 440832, dtype: float64

In [114]:
from sklearn.impute import SimpleImputer

In [115]:
imputer=SimpleImputer(strategy="median")

In [116]:
data_num=data.select_dtypes(include=[np.number])

In [117]:
x=imputer.fit_transform(data_num)

In [118]:
data_num=pd.DataFrame(x,columns=data_num.columns,index=data_num.index)

In [119]:
data_num

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0
...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0

In [120]:
data=pd.DataFrame(data,columns=["Gender","Subscription type","Contract Spend"],index=data.index)

In [121]:
data.head()

   Gender  Subscription type  Contract Spend
0  Female                NaN             NaN
1  Female                NaN             NaN
2  Female                NaN             NaN
3    Male                NaN             NaN
4    Male                NaN             NaN

In [122]:
data_cat=df[["Gender","Subscription Type","Contract Length"]].copy()

In [123]:
data_cat

        Gender Subscription Type Contract Length
0       Female          Standard          Annual
1       Female             Basic         Monthly
2       Female             Basic       Quarterly
3         Male          Standard         Monthly
4         Male             Basic         Monthly
...        ...               ...             ...
440828    Male           Premium          Annual
440829  Female           Premium          Annual
440830    Male          Standard       Quarterly
440831    Male          Standard       Quarterly
440832    Male           Premium       Quarterly

[440832 rows x 3 columns]

In [124]:
gender=data_cat[["Gender"]]

In [125]:
gender

        Gender
0       Female
1       Female
2       Female
3         Male
4         Male
...        ...
440828    Male
440829  Female
440830    Male
440831    Male
440832    Male

[440832 rows x 1 columns]

In [126]:
from sklearn.preprocessing import LabelEncoder

In [127]:
encoder=LabelEncoder()

In [128]:
data_encoder=encoder.fit_transform(gender)

C:\Users\q\anaconda3\envs\omenv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [129]:
gender_df = pd.DataFrame(data_encoder, columns=['Gender'],index=gender.index)

In [130]:
from sklearn.preprocessing import OneHotEncoder

In [131]:
encod=OneHotEncoder()

In [132]:
data_cats=data_cat[["Subscription Type","Contract Length"]]

In [133]:
data_cats

       Subscription Type Contract Length
0               Standard          Annual
1                  Basic         Monthly
2                  Basic       Quarterly
3               Standard         Monthly
4                  Basic         Monthly
...                  ...             ...
440828           Premium          Annual
440829           Premium          Annual
440830          Standard       Quarterly
440831          Standard       Quarterly
440832           Premium       Quarterly

[440832 rows x 2 columns]

In [134]:
data_code=encod.fit_transform(data_cats)

In [135]:
data_code.toarray()

array([[0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.]], shape=(440832, 6))

In [136]:
data_coder=pd.DataFrame(data_code.toarray(),columns=['Basic', 'Premium', 'Standard','Annual', 'Monthly', 'Quarterly'],index=data_cats.index)

In [137]:
data_coder

        Basic  Premium  Standard  Annual  Monthly  Quarterly
0         0.0      0.0       1.0     1.0      0.0        0.0
1         1.0      0.0       0.0     0.0      1.0        0.0
2         1.0      0.0       0.0     0.0      0.0        1.0
3         0.0      0.0       1.0     0.0      1.0        0.0
4         1.0      0.0       0.0     0.0      1.0        0.0
...       ...      ...       ...     ...      ...        ...
440828    0.0      1.0       0.0     1.0      0.0        0.0
440829    0.0      1.0       0.0     1.0      0.0        0.0
440830    0.0      0.0       1.0     0.0      0.0        1.0
440831    0.0      0.0       1.0     0.0      0.0        1.0
440832    0.0      1.0       0.0     0.0      0.0        1.0

[440832 rows x 6 columns]

In [138]:
data_num

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0
...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0

In [139]:
df=pd.concat([data_num,data_coder],axis=1)

In [140]:
df

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Basic,Premium,Standard,Annual,Monthly,Quarterly
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,0.0,0.0,1.0,1.0,0.0,0.0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,0.0,0.0,0.0,1.0,0.0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,0.0,0.0,0.0,0.0,1.0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0,0.0,0.0,1.0,0.0,1.0,0.0
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0,0.0,1.0,0.0,1.0,0.0,0.0
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,1.0,0.0,1.0,0.0,0.0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0,0.0,0.0,1.0,0.0,0.0,1.0
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0,0.0,0.0,1.0,0.0,0.0,1.0
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0,0.0,1.0,0.0,0.0,0.0,1.0

In [141]:
data_encoder

array([0, 0, 0, ..., 1, 1, 1], shape=(440832,))

In [142]:
df

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Basic,Premium,Standard,Annual,Monthly,Quarterly
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,0.0,0.0,1.0,1.0,0.0,0.0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,0.0,0.0,0.0,1.0,0.0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,0.0,0.0,0.0,0.0,1.0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0,0.0,0.0,1.0,0.0,1.0,0.0
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0,0.0,1.0,0.0,1.0,0.0,0.0
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,1.0,0.0,1.0,0.0,0.0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0,0.0,0.0,1.0,0.0,0.0,1.0
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0,0.0,0.0,1.0,0.0,0.0,1.0
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0,0.0,1.0,0.0,0.0,0.0,1.0

In [143]:
df=pd.concat([df,gender_df],axis=1)

In [144]:
df

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Basic,Premium,Standard,Annual,Monthly,Quarterly,Gender
0,2.0,30.0,39.0,14.0,5.0,18.0,932.00,17.0,0.0,0.0,1.0,1.0,0.0,0.0,0
1,3.0,65.0,49.0,1.0,10.0,8.0,557.00,6.0,1.0,0.0,0.0,0.0,1.0,0.0,0
2,4.0,55.0,14.0,4.0,6.0,18.0,185.00,3.0,1.0,0.0,0.0,0.0,0.0,1.0,0
3,5.0,58.0,38.0,21.0,7.0,7.0,396.00,29.0,0.0,0.0,1.0,0.0,1.0,0.0,1
4,6.0,23.0,32.0,20.0,5.0,8.0,617.00,20.0,1.0,0.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,54.0,15.0,1.0,3.0,716.38,8.0,0.0,1.0,0.0,1.0,0.0,0.0,1
440829,449996.0,25.0,8.0,13.0,1.0,20.0,745.38,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0
440830,449997.0,26.0,35.0,27.0,1.0,5.0,977.31,9.0,0.0,0.0,1.0,0.0,0.0,1.0,1
440831,449998.0,28.0,55.0,14.0,2.0,0.0,602.55,2.0,0.0,0.0,1.0,0.0,0.0,1.0,1
440832,449999.0,31.0,48.0,20.0,1.0,14.0,567.77,21.0,0.0,1.0,0.0,0.0,0.0,1.0,1

In [145]:
from sklearn.preprocessing import StandardScaler

In [146]:
scaler=StandardScaler()

In [147]:
df_scale=scaler.fit_transform(df)

In [148]:
df_scale=pd.DataFrame(df_scale,columns=df.columns,index=df.index)

In [149]:
df_scale

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Basic,Premium,Standard,Annual,Monthly,Quarterly,Gender
0,-1.740088,-0.753326,0.448760,-0.210511,0.454549,0.609620,1.247427,0.293052,-0.693012,-0.713374,1.398594,1.219751,-0.496232,-0.817258,-1.145909
1,-1.740080,2.059646,1.028278,-1.724562,2.083100,-0.601319,-0.309865,-0.986584,1.442976,-0.713374,-0.715004,-0.819839,2.015188,-0.817258,-1.145909
2,-1.740072,1.255940,-1.000036,-1.375166,0.780259,0.609620,-1.854698,-1.335575,1.442976,-0.713374,-0.715004,-0.819839,-0.496232,1.223604,-1.145909
3,-1.740065,1.497051,0.390808,0.604748,1.105969,-0.722413,-0.978462,1.689018,-0.693012,-0.713374,1.398594,-0.819839,2.015188,-0.817258,0.872670
4,-1.740057,-1.315921,0.043097,0.488282,0.454549,-0.601319,-0.060698,0.642043,1.442976,-0.713374,-0.715004,-0.819839,2.015188,-0.817258,0.872670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440828,1.733909,0.211121,1.318037,-0.094045,-0.848291,-1.206788,0.352005,-0.753923,-0.693012,1.401789,-0.715004,1.219751,-0.496232,-0.817258,0.872670
440829,1.733917,-1.155179,-1.347747,-0.326976,-0.848291,0.851808,0.472436,-1.451906,-0.693012,1.401789,-0.715004,1.219751,-0.496232,-0.817258,-1.145909
440830,1.733925,-1.074809,0.216952,1.303541,-0.848291,-0.964600,1.435589,-0.637592,-0.693012,-0.713374,1.398594,-0.819839,-0.496232,1.223604,0.872670
440831,1.733932,-0.914068,1.375989,-0.210511,-0.522581,-1.570070,-0.120706,-1.451906,-0.693012,-0.713374,1.398594,-0.819839,-0.496232,1.223604,0.872670
440832,1.733940,-0.672956,0.970326,0.488282,-0.848291,0.125245,-0.265139,0.758374,-0.693012,1.401789,-0.715004,-0.819839,-0.496232,1.223604,0.872670

In [150]:
from sklearn.linear_model import LogisticRegression

In [151]:
model=LogisticRegression()

In [152]:
model.fit(df_scale,data_labels)

LogisticRegression()

In [153]:
prediction=model.predict(df_scale)

In [154]:
accuracy=model.score(df_scale,data_labels)

In [155]:
accuracy

0.9806025878339141

In [156]:
prediction

array([1., 1., 1., ..., 0., 0., 0.], shape=(440832,))

In [157]:
test=pd.read_csv("test_data.csv")

In [158]:
test

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,Female,33,12,6,21,Basic,Quarterly,947,14,1
64370,64371,37,Male,6,1,5,22,Standard,Annual,923,9,1
64371,64372,25,Male,39,14,8,30,Premium,Monthly,327,20,1
64372,64373,50,Female,18,19,7,22,Standard,Monthly,540,13,1
64373,64374,52,Female,45,15,9,25,Standard,Monthly,696,22,1

In [159]:
y_test=test.drop("Churn",axis=1)
y_pre=test["Churn"]

In [160]:
y_test

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20
2,3,47,Male,27,10,2,29,Premium,Annual,757,21
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18
4,5,53,Female,58,24,9,2,Standard,Annual,533,18
...,...,...,...,...,...,...,...,...,...,...,...
64369,64370,45,Female,33,12,6,21,Basic,Quarterly,947,14
64370,64371,37,Male,6,1,5,22,Standard,Annual,923,9
64371,64372,25,Male,39,14,8,30,Premium,Monthly,327,20
64372,64373,50,Female,18,19,7,22,Standard,Monthly,540,13
64373,64374,52,Female,45,15,9,25,Standard,Monthly,696,22

In [161]:
from sklearn.ensemble import RandomForestClassifier

In [162]:
model=RandomForestClassifier()

In [163]:
model.fit(df_scale,data_labels)

RandomForestClassifier()

In [164]:
prediction=model.predict(df_scale)

In [165]:
accuracy=model.score(df_scale,data_labels)

In [166]:
accuracy

1.0

In [167]:
model=RandomForestClassifier()

model.predict(y_test)

In [168]:
model.fit(df_scale,data_labels)

RandomForestClassifier()

In [169]:
data_labels

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
440828    0.0
440829    0.0
440830    0.0
440831    0.0
440832    0.0
Name: Churn, Length: 440832, dtype: float64